/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package util.time.sequence.timerclock.nativelinux;

public class linuxclock {
  public static void set_ticktime_nanos(int nanos) {
    linuxclockJNI.set_ticktime_nanos(nanos);
  }

  public static void next_tick() {
    linuxclockJNI.next_tick();
  }

  public static int scheduleRealtime(int prio) {
    return linuxclockJNI.scheduleRealtime(prio);
  }

  public static int scheduleFIFO(int prio) {
    return linuxclockJNI.scheduleFIFO(prio);
  }

  public static int scheduleOther(int prio) {
    return linuxclockJNI.scheduleOther(prio);
  }

  public static int getScheduler() {
    return linuxclockJNI.getScheduler();
  }

  public static int getPriority() {
    return linuxclockJNI.getPriority();
  }

}
